### ISSUE TITLE
Raise awareness of https://gitter.im/trueos/Lobby/archives

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-docs#10]
https://www.trueos.org/handbook/help.html#trueos-gitter-channel draws attention to the lobby and assumes that readers will log in. 

For readers who wish to browse without logging in, https://gitter.im/trueos/Lobby offers no hint about the existence of https://gitter.im/trueos/Lobby/archives

Please consider adding, to the handbook, a link to the archives.

**Comment by Mrt134** [comment]
Thanks for reporting this - I thought I had forgotten documenting something about Gitter :). I added a full description of the archive and a link to the appropriate section of the handbook.
