### ISSUE TITLE
User guide: fix the link for GELI

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-docs#11]
https://www.trueos.org/handbook/advanced.html#using-the-text-installer

> … FreeBSD GELI framework. …

The linked word refers to 
https://www.freebsd.org/cgi/man.cgi?query=geli/qgit/ 

If referring to the manual page, better to refer to 
https://www.freebsd.org/cgi/man.cgi?query=geli&sektion=8&manpath=FreeBSD+12-current 
or – assuming future uses of TrueOS Desktop on FreeBSD _11_ – 
https://www.freebsd.org/cgi/man.cgi?query=geli&sektion=8&manpath=FreeBSD

**Comment by Mrt134** [comment]
Thanks for pointing this out. I've updated the link and it should be working again.
