### ISSUE TITLE
Explain kernel.old

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-docs#12]
https://www.trueos.org/handbook/postinstall.html#bsd-boot-loader mentions kernels but does not describe any situation where `kernel.old` might be appropriate. 

Can an .old kernel apply to any new or old boot environment? 

Re: discussion around https://discourse.trueos.org/t/-/230/4?u=grahamperrin might an .old kernel become a sibling to nonstandard flavours of the kernel?

And so on.

**Comment by pkgdemon** [comment]
When you build a custom kernel.  Your previous kernel gets copied to kernel.old.  So you can boot to it in case of failure.

**Comment by Mrt134** [comment]
I've updated postinstall.rst with additional text explaining kernel.old is available for users who create a custom kernel and should save kernel.old as a backup.
