### ISSUE TITLE
Guide: outdated direction to use 'portsnap fetch extract'

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-docs#13]
https://www.trueos.org/handbook/support.html?highlight=git%20fetch#getting-the-source-code

> … ensure the Ports Collection is installed as the superuser, using `portsnap fetch extract` …

https://www.trueos.org/handbook/using.html?highlight=ports#freebsd-ports more accurately, 

> It is possible to pull in ports from the FreeBSD project using portsnap, but this is currently not recommended for TrueOS®. … 

(Did I _imagine_ seeing `git fetch` elsewhere in the Guide a few days or weeks ago?)

**Comment by pkgdemon** [comment]
We have discussed in the past adding a wrapper to this command so it just does the right thing.  I would just remove it but it is part of the freebsd-runtime package so we cannot skip installing it yet.  It has been on the list of things to address.  Just lower on the priority list.  I might look over the portsnap script to see if its an easy fix.

**Comment by Mrt134** [comment]
Thanks for spotting this! I've updated the handbook to fix the discrepancy.
