### ISSUE TITLE
Installer upgrade UI has changed; docs need to be updated

### ISSUE THREAD

**Issue by baitisj** [trueos/trueos-docs#14]
The workflow is now different
[Handbook - Upgrading](https://www.trueos.org/handbook/sysadmclient.html#upgrading-from-pcbsd-10-x-to-trueos)

The current UI looks like this
![install1a](https://cloud.githubusercontent.com/assets/12502877/20894837/d3977e7a-bacb-11e6-8fea-1ee782f497ea.png)

**Comment by baitisj** [comment]
Also, note that `pc-sysinstaller` in trueos/trueos-utils-qt5 is not resizing the dropdown widget correctly in above screenshot
I cannot figure out how to make this into a separate issue

**Comment by Mrt134** [comment]
Thanks for pointing this out - section is now updated!
