### ISSUE TITLE
Document PersonaCrypt support for PEFS

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-docs#15]
I'd love to see (might become **desperate** for) user-friendly documentation that focuses on using **PEFS with PersonaCrypt**.

From https://www.trueos.org/changelog/ (but https://github.com/trueos/trueos-changelog/issues/1 please note that the log refers to commits that are not found):

> Tue Sep 6 17:22:06 PDT 2016
> 
> Add PEFS support to personacrypt. This means you can have an encrypted home-directory without external media using the PEFS framework.
> 
> Keys are split into two (as with GELI), with a passphrase and key fragment on disk. Be SURE to backup or print out the key fragment on disk.
> 
> Support for PCDM will be added soon(ish)! 
> 
> https://github.com/trueos/personacrypt-cf245d2abb0a1f9784c476433d80af43ec17e041/commit/

> Tue Sep 20 11:52:28 PDT 2016
> 
> Add support to PersonaCrypt to import/export PEFS type encrypted home dirs.
> 
> https://github.com/trueos/personacrypt-64bf45d703b9e0fb46973e7c930e67970aebe16d/commit/

> Tue Sep 20 12:42:12 PDT 2016
> 
> Add prelim support to personacrypt for PEFS+SYNCTHING
> 
> This will allow setting up a PEFS encrypted home-directory along with a SyncThing target of the encrypted contents. When exporting and importing the user setting, the SyncThing Client ID's and folder ID's will be preserved, alowing the linking of a users $HOME directory between more than one system.
> 
> https://github.com/trueos/personacrypt-cbe6332b3cc944dd3a0708c5188dc48fabf23b33/commit/

### Side note: PCDM, Syncthing

From my point of view: 

- no urgency for PCDM to support PEFS
- no urgency for documentation about Syncthing with PersonaCrypt (or with any other aspect of TrueOS); I'll make a separate issue. 

### Discussions

[PersonaCrypt, PEFS, Syncthing, multiplatform ZFS encryption and the User Guide](https://forums.pcbsd.org/thread-20981.html) (2016-10-02) – PC-BSD Forums – with reference to more recent [Approaches to encryption with ZFS - The Lounge - TrueOS Community](https://discourse.trueos.org/t/-/234)

https://gitter.im/trueos/Lobby?at=584618b80da034021b733525 with a thumbs-up from @cryptorick

> A PEFS for PersonaCrypt walkthrough for dummies would be nice to have.

**Comment by Mrt134** [comment]
Thanks for pointing this out - PEFS support in SysAdm is now documented, and I got Ken to add PEFS initialisation to the SysAdm user manager at the same time (available soon).
