### ISSUE TITLE
Document TrueOS uses of Syncthing (with, for example, PersonaCrypt)

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-docs#16]
Separate from PEFS-focused https://github.com/trueos/trueos-docs/issues/15

We can take a more leisurely approach to documenting uses of [Syncthing](https://syncthing.net/). 

From https://www.trueos.org/changelog/

> prelim support to personacrypt for PEFS+SYNCTHING
> 
> This will allow setting up a PEFS encrypted home-directory along with a SyncThing target of the encrypted contents. When exporting and importing the user setting, the SyncThing Client ID's and folder ID's will be preserved, alowing the linking of a users $HOME directory between more than one system.

#2 (comment)

> … we will address PEFS and Syncthing once some other issues are resolved.

**Comment by Mrt134** [comment]
Discussed this with Kris; Syncthing isn't ready for documentation yet, as it is still "experimental" for the moment. It has also moved down the priority list (mostly due to openrc). We'll revisit Syncthing a little farther down the road.
