### ISSUE TITLE
Make clear the value of booting, not simply creating, a new boot environment

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-docs#17]
https://www.trueos.org/handbook/sysadmclient.html#boot-environment-manager

> **Create BE**: Creates a new boot environment. Do this before making any changes to the system that may impact on your current boot environment. You will be prompted for a name which can only contain letters or numbers. Click OK to create the environment, then the system will add it to the list of boot environments.

If that set of instructions is followed, and if the user proceeds to spoil the current environment, then (if I understand correctly) it may be appropriate/necessary to roll _forward_ to a more recent environment: 

- that 'feels' counterintuitive to the accepted wisdom of rolling _back_ to regain goodness. 

## Enhancement request

Please consider extending the guidance. Essentially: 

- activate the new environment
- restart TrueOS
- be prepared to roll back to, and activate, the previous environment (if changes that you make following restart have an undesirable impact on the system). 

– or words to that effect. 

Note, the word _undesirable_; because "changes to the system" _should always_ have an impact on the system. Distinguish between positive/desirable and negative/undesirable impacts.

**Comment by Mrt134** [comment]
I'm currently reviewing the full TrueOS handbook to fix a few other issues, but I will look into this once I get to the SysAdm section.

**Comment by Mrt134** [comment]
I tried to clean up the section and help it flow a little better, thanks for reporting this.
