### ISSUE TITLE
Order of guidance at e.g. sysadmclient.html#boot-environment-manager

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-docs#18]
A thought/suggestion …

https://www.trueos.org/handbook/sysadmclient.html#boot-environment-manager

1. first and foremost the concise, simple explanation of the seven buttons
2. screenshot putting the seven in context
3. background information and more detailed, relatively complex explanations

– compare with the current order of things, which places simplicity [amidst complexity](https://github.com/trueos/trueos-docs/blob/188b4108d8c43fbde1eaeba40d3f6d03a4820da1/trueos-handbook/sysadmclient.rst#boot-environment-manager).

**Comment by Mrt134** [comment]
I'm currently reviewing the full TrueOS handbook to fix a few other issues, but I will look into this once I get to the SysAdm section.

**Comment by Mrt134** [comment]
Cleaned up the section; hopefully it will read a little better now. Thanks for the report.
