### ISSUE TITLE
Add chapter discussing `openrc` usage

### ISSUE THREAD

**Issue by baitisj** [trueos/trueos-docs#19]
As migration to `openrc` has some pretty clear changes from normal BSD, a user guide chapter that coalesces knowledge from Discourse seems appropriate.

I'm going to add some links from Discourse from which to draw information.

**Comment by baitisj** [comment]
Migration:
https://discourse.trueos.org/t/openrc-migration/315

rc.conf.trueos / rc.conf:
https://discourse.trueos.org/t/etc-rc-conf-d-and-proper-settings-with-reference-to-rc-conf-5/193/2
https://gitter.im/trueos/Lobby?at=585440d296a565f84405b17e

**Comment by Mrt134** [comment]
Looking into this now.

**Comment by grahamperrin** [comment]
Thanks folks. Please be aware that I have linked to the _work in progress_ from https://discourse.trueos.org/t/-/389/5 with a plea, 

> if you bookmark that, please also bookmark and prefer the point in the published guide where the finished content will appear. 

Reference to the work in progress was, I hope, a suitable response where AFAICT we have a user attempting to start a service that is not yet OpenRC-ready. Or words to that effect.

**Comment by Mrt134** [comment]
Ok, I've reviewed the chapter as it stands with jmaloney, and he's given his blessing, with the caveat that some changes are happening as the work continues. I'll continue to track development and update as necessary.
