### ISSUE TITLE
The blue alert about the need to recreate user accounts appears relatively late, it should become a forewarning

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-docs#2]
https://www.trueos.org/handbook/sysadmclient.html#upgrading-from-pc-bsd-10-x-to-trueos 

> **!** 
> When you get to the Create a User Screen, recreate the primary user account using the same name you used on your PC-BSD® system so that TrueOS® can associate the existing home directory with that user. Once you have logged in, you can use User Manager to recreate any other user accounts or to reassociate any PersonaCrypt accounts.

That blue alert currently appears at the _end_ of the sub-section. We should not assume that users will read that far, and realise all implications, before proceeding with installation. 

(For PersonaCrypt users, the warning may be **critical**. If the required key is not saved safely elsewhere before installation begins overwriting things, then how will the user regain access to their home directory? And so on.)

Please bring this blue alert forward, to be a *fore*warning. 

Thanks

**Comment by baitisj** [comment]
@grahamperrin I put a warning up at the front. Please take a peek. Do ALL personacrypt users need to have their keys backed so that the installer can re-associate the user directories? If so, we should change the passage to reflect this.

Nice find, btw. Seems pretty critical.

**Comment by grahamperrin** [comment]
Thanks, 

> a safe place (e.g. a thumb drive) 

– I imagine someone treating their PersonaCrypt thumb drive as the safe place 
:-0 
so maybe we should make unmistakably clear that the key should be saved elsewhere. 

----

Revisiting an earlier thought, 

> If the required key is not saved safely elsewhere before installation begins overwriting things, then how will the user regain access to their home directory? 

The simplest answer _might_ be: 

- use an earlier boot environment to regain access

– however I have not tested that theory. 

----

I'll follow-up with a post to the forums.

**Comment by grahamperrin** [comment]
From [PersonaCrypt, PEFS, Syncthing, multiplatform ZFS encryption and the User Guide](https://forums.pcbsd.org/thread-20981.html):

> a. it _will_ be good for the Guide now to mention preliminary support for [PEFS](http://pefs.io/) and [Syncthing](https://syncthing.net/)
> 
> b. it _may_ be good for the Guide to mention the future possibility of support for multiplatform encryption.
> 
> Simple mentions, without going into detail. …

**Comment by Mrt134** [comment]
Thanks for the issue and discussion - primary issue is now resolved (thank you baitisj!), and we will address PEFS and Syncthing once some other issues are resolved.
