### ISSUE TITLE
Now that openrc is used, we are using some non-base-system services by default

### ISSUE THREAD

**Issue by baitisj** [trueos/trueos-docs#20]
For example:
Although they look compatible, FreeBSD's `ntpd` installed in the base system (but not enabled by default) is different from TrueOS' `openntpd` (enabled by default).

**Comment by Mrt134** [comment]
Looking into this now, thanks for drawing attention to it!

**Comment by Mrt134** [comment]
Ok, I've added a table and extra information to the comparison section between TrueOS and FreeBSD. Everything has to have a caveat about ongoing development for now, but there is now a solid place in the handbook for this information as it is now and when it changes. Thanks for bringing this up!
