### ISSUE TITLE
https://gitter.im/trueos in lieu of https://gitter.im/trueos/Lobby

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-docs#23]
## Enhancement request

After https://github.com/gitterHQ/gitter/issues/1571 is fixed or closed, please habitually refer: 

- to https://gitter.im/trueos
- not to https://gitter.im/trueos/Lobby

– thanks. 

## Rationale

Raise awareness of the choice of venues. 

As in the real world _not everything_ can happen in a lobby (too crowded, too much noise), so – in an online chat environment – not everything should _begin_ in a lobby. 

## Background

[Chat room for troubleshooting](https://discourse.trueos.org/t/chat-room-for-troubleshooting/342?u=grahamperrin) (2016-12-09) – the room was created by @kmoore134 following a private chat. Not in that topic, there was understandably some initial YA concern along the lines of "Oh, no!"" _yet another area to keep track of_ but all things considered, I reckon that the split has worked out reasonably well: 

- a good proportion of troubles, with natural noise and some technobabble, in one area
- a less noisy lobby, which should be more appealing to newcomers, especially if (as expected with TrueOS Desktop) some of these individuals will begin with relatively technical knowledge. 

(I saw only one incident of rough handling of a newcomer. Inappropriate but it was a one-off, at what might have been a busy time of the month, so I didn't challenge the misbehaviour.)

### 1

https://www.trueos.org/handbook/preface.html#preface-and-legal

### 3

https://www.trueos.org/handbook/preinstall.html#obtaining-trueos

### 5

https://www.trueos.org/handbook/postinstall.html#installation-troubleshooting

Here it's tempting to be specific with https://gitter.im/trueos/troubleshooting for troubleshooting but I reckon, https://gitter.im/trueos for consistency. At the overview of rooms, it's easy enough to see the word _troubleshooting_.

### 14

https://www.trueos.org/handbook/help.html#trueos-gitter-channel

Incidentally, 

> … To access the Gitter archive, navigate to the TrueOS® archive. …

Strictly speaking there are **multiple archives**, one per room. At https://github.com/gitterHQ/gitter/issues/ one of the search-related enhancement requests should cover the wish for a single search to span all rooms within an organisation e.g. https://gitter.im/trueos

**Comment by Mrt134** [comment]
Updated, thanks!

**Comment by grahamperrin** [comment]
https://www.trueos.org/handbook/help.html#trueos-gitter-channel has disappeared; https://www.trueos.org/handbook/helpsupport.html#gitter-chat directs people to the lobby without making them aware of the troubleshooting area, so there's unnecessary noise in the lobby.

**Comment by Mrt134** [comment]
I'm not going to reopen this issue, but I have fixed the regression in the Gitter section regarding pointing to the Lobby vs the wider Rooms list.

As for the other instances in helpsupport.rst pointing to the Gitter Lobby:
 (1) They are pointing to the Lobby as an option to introduce yourself when starting to contribute to TrueOS (proper usage), and
 (2) We don't have (and probably won't, by virtue of the current translation community size) have a **Translation** room in Gitter, so the Lobby is still the best (Gitter) option for new/current translators to interact with each other and the devs.
