### ISSUE TITLE
Required but not excessive use of characters such as ® and ™

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-docs#24]
## Enhancement request

Less aggressive use of the characters at https://www.trueos.org/handbook/trueos.html and elsewhere. 

### Expected exceptions

https://www.trueos.org/handbook/trueos.html where (I guess) the lists of contents draw from titles, some of which properly include a special character.

The [Copyright & Trademarks](https://www.trueos.org/handbook/preface.html#copyright-trademarks) section _only_ of the preface to the guide.

## Rationale

It looks peculiar. I get it, I get it, I get it, I get it, I get it. 

I get it, it's a registered trademark :-) 

The rrrrrepetition is probably _quietly viewed as peculiar_ or over-the-top by other people, too …

## Reference

For example, the United States Postal Service (USPS) [Guidelines to Proper Trademark Use](https://ribbs.usps.gov/forms/documents/tech_guides/GUIDELINES_TO_TRADEMARK_USE.PDF) version 1 (2008-03-25) page 2, with added emphasis:

> **PROPER USE OF TRADEMARKS** 
> 
> … On Web pages and slide presentations, registered trademark and trademark symbols should be noted on the **first occurrence** on every page registrations and trademarks appear. 

Thanks :+1:

**Comment by Mrt134** [comment]
The use of registered trademark symbols is being followed according to stipulations laid down by iX Systems/its lawyers. I've attempted to make them smaller/less distracting, but I'm not allowed to remove them altogether.

**Comment by grahamperrin** [comment]
Fair enough, 
fair enough. 
fair enough :-)

Thanks for the explanation, I just never saw any other organisation use the symbols so profusely. (The once-per-page, first occurrence convention seems more normal.)
