### ISSUE TITLE
After the GELI with GPT page of TrueOS Disk Wizard is fixed, update (at least) the shot in the guide

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-docs#26]
1. https://github.com/trueos/trueos-core/issues/254 
2. after that page of the wizard is updated, take a screenshot (in a virtual machine, I guess)
3. https://www.trueos.org/handbook/install.html#install11 update the shot
4. consider related wording in the guide, update if necessary. 

Thanks

**Comment by Mrt134** [comment]
All done, thanks!
