### ISSUE TITLE
Guidance to run flashpluginctl results in misleading guidance to install outdated www/linux-c6-flashplugin10

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-docs#28]
Version 10 is seriously outdated. 

The norm is (or should be) the port of Adobe's released version 24.0.0.186. 

In context: 

> … If Adobe Flash does not seem to be working, running **`flashpluginctl`** on as the regular user account should fix the problem.

– https://github.com/trueos/trueos-docs/blob/287d9681b3be9ee1d1ef9b9f94c8407938434d70/trueos-handbook/using.rst#java-and-flash 

```
$ date ; uname -v ; uname -n
Sun  1 Jan 2017 11:26:25 GMT
FreeBSD 12.0-CURRENT #12 5ef9376(drm-next-4.7): Thu Dec 29 16:26:36 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk
$ flashpluginctl on
file /usr/local/lib/browser_plugins/linux-c6_64-flashplugin/libflashplayer.so not found. Please install port 'www/linux-c6-flashplugin10'
$ 
```

There was report of problems: ["flashpluginctl on" looking for wrong directory?](https://discourse.trueos.org/t/flashpluginctl-on-looking-for-wrong-directory/501?u=grahamperrin)

> I am having problems getting Flash to work properly. …

> Running "flashpluginctl on" gives the following
> `[ken@kenstrueos-2554] ~% flashpluginctl on`
> `file /usr/local/lib/browser_plugins/linux-c6_64-flashplugin/libflashplayer.so not found. Please install port 'www/linux-c6-flashplugin10'`

## Enhancement to the guide

With emerging changes (maybe `flashplayer-24.0` and/or `linux-flashplayer-24.0.0.186`) I can't guess **whether use of `flashpluginctl` will be advisable** in the future. 

If advisable, then I guess that: 

1. the guide should forewarn users to ignore guidance about linux-c6-flashplugin10; to **not** install that port; and/or 
2. there should be a change to the guidance that is offered by `flashpluginctl. 

## `flashpluginctl`

```
$ pkg search flashpluginctl
$ man flashpluginctl
No manual entry for flashpluginctl
$ flashpluginctl --help
file /usr/local/lib/browser_plugins/linux-c6_64-flashplugin/libflashplayer.so not found. Please install port 'www/linux-c6-flashplugin10'
$ 
```

– and I can not find `flashpluginctl` in FreshPorts, or [in FreeBSD manual pages](https://www.freebsd.org/cgi/man.cgi?query=flashpluginctl). Is/was it a PC-BSD/TrueOS product?

**Comment by Mrt134** [comment]
Thanks for posting this. I've had a full rework of "using.rst" on my "to-do" list for a while, and finally have some time to look into the file. Getting flash up to speed seems a good place to start :).

**Comment by Mrt134** [comment]
Update: flash support is in a state of flux right now as the devs continue to work on Linux emulation and other issues. I've been advised to refrain from a full update of this section until some of these issues are resolved. In the meantime, I'll be putting a notification box in the handbook explaining this and providing some informative links.

**Comment by Mrt134** [comment]
Apologies, I forgot to close this with commit 263581bbf46c5206fef214e89fa20d9eb23ea23f

Flash install instructions are updated and tested.
