### ISSUE TITLE
Installers: misleading guidance to write the content of an .iso to a USB flash drive 

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-docs#29]
From https://www.trueos.org/handbook/preinstall.html#writing-to-a-usb-device: 

> … Launch `win32-image-writer.exe` to start the Win32 Disk Imager utility, shown in Figure 2.5.1. Use browse to browse to the location of the `.iso` …

– and: 

> … To burn the `.iso` file on Mac OS X, insert a USB stick …

Credit: den at https://discourse.trueos.org/t/pre-installation-questions/711?u=grahamperrin

**Comment by Mrt134** [comment]
Thanks for bringing this to my attention - error is fixed.
