### ISSUE TITLE
The handbook should forewarn that problems may occur if the frequency of snapshots is too high for replication

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-docs#3]
https://www.trueos.org/handbook/sysadmclient.html#schedules-tab

From https://github.com/trueos/lpreserver/issues/4#issuecomment-247120066

>  somewhat common when using the "auto" snapshot schedule, since the snapshots are happening at a faster rate than you can replicate them. 

Incidentally, I don't see an _auto_ option.

**Comment by Mrt134** [comment]
Thanks for the report - added a note to the handbook about the issue.

**Comment by grahamperrin** [comment]
Thanks. End result https://www.trueos.org/handbook/sysadmclient.html#replication-tab
