### ISSUE TITLE
Google's index of the guide is outdated

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-docs#31]
https://www.trueos.org/handbook/searchresults.html?q=portsnap for example. 

![search trueos user guide](https://cloud.githubusercontent.com/assets/192271/23091201/45b1c454-f5a8-11e6-88a9-68b2bb461de4.png)

**Comment by JoshDW19** [comment]
Indexing of the handbook requested since there have been some structural changes to the handbook.  We need to keep in mind this is like a live website and if we have any major changes to the structure then we have to request google recrawl the website.  Thanks!
