### ISSUE TITLE
2.5.1 VM Creation doesn't mention anything about EFI

### ISSUE THREAD

**Issue by chief1983** [trueos/trueos-docs#32]
In setting up a VirtualBox machine for the 22 Feb 2017 DVD image, I could not get it to load the GUI until I realized I needed to check System -> Motherboard -> Enable EFI in the machine settings.  A note about this in the docs could be very useful, as selecting the FreeBSD 64-bit profile in the latest VirtualBox (5.1.16) does not enable that option automatically.

**Comment by Mrt134** [comment]
Thanks for letting me know, I'll work on a fix and update the docs shortly!

**Comment by Mrt134** [comment]
Ok, I've got notes added in the preinstall/virtualization and helpsupport/troubleshooting sections. I'll trigger a new build and upload of the docs, so the updates should be visible tomorrow!
