### ISSUE TITLE
Update trueos/* README.md files

### ISSUE THREAD

**Issue by Mrt134** [trueos/trueos-docs#34]
Each trueos repo needs its readme filed reviewed.
Additionally, instructions on how to file new issues and feature requests needs to be included in each readme.

**Comment by q5sys** [comment]
I can help with this.

**Comment by Mrt134** [comment]
Cool, any help is appreciated!

**Comment by Mrt134** [comment]
First draft of a generic README.MD file for a TrueOS Project repo is added to the pcdm repository: https://github.com/trueos/pcdm.

Feedback is always welcome! Barring any blockers, I will be adding either this readme file or information from it to the readme files in the other trueos/* repositories.

**Comment by Mrt134** [comment]
Ok, with the exception of a few forked repos (freebsd, tdesktop, etc.). All TrueOS project repos now have a README.md file with a TrueOS general project info section/TOC.
