### ISSUE TITLE
Handbook: Dual-booting clarification

### ISSUE THREAD

**Issue by Mrt134** [trueos/trueos-docs#35]
_From @danboid on May 25, 2017 13:46_

https://www.trueos.org/handbook/install.html#dual-booting

The dual-booting chapter of the handbook is all a bit vague and I expect outdated too.

From my recent resarch into this I THINK dual-booting TrueOS with Linux should be possible once tsoom's chainloading patch for the FreeBSD bootloader is merged. He tells me it works and is ready to go, pretty much.  He just needs to check the licensing IIRC.

Would dualbooting with Windows be possible on a single drive machine? I'm not sure it would as I think both TrueOS and Windows want to control the bootsector. Maybe dual-booting with Windows will be possible on machines with multiple drives?

_Copied from original issue: trueos/trueos-core#1430_

**Comment by Mrt134** [comment]
The Dual booting section is already on my list for review. :)
I did have TrueOS dual booted with Windows on my laptop at one time in the last year, but I did have multiple drives to simplify the process.

**Comment by Mrt134** [comment]
Ok, I've reviewed and updated the section with input from the other devs. It should better explain what TrueOS can and can't do for dual booting, and includes a recommendation for partitioning a disk before installing operating systems.

According to the devs, dual booting TrueOS with a single drive and even multiple other operating systems (one has a system with TrueOS/Windows/Mint installed on a single disk) is workable. In the case with Windows, while it may seem that both systems compete for the bootsector, TrueOS using rEFInd provides user control over what OS boots and prevents conflicts.

**Comment by danboid** [comment]
Hi Tim!

I can't see any changes on https://www.trueos.org/handbook/install.html#dual-booting since I posted this ticket.

So you can only dual-boot TrueOS if you have a UEFI machine, BIOS users are out of luck currently?

**Comment by q5sys** [comment]
@danboid FYI, it'll take a bit until the changes go public.  We build new docs at intervals.

**Comment by Mrt134** [comment]
@danboid  - q5sys is correct; the updated handbook will be visible after the next build/push.
As for dual-boot with BIOS, now that we use rEFInd as the TrueOS Boot Manager, the project doesn't technically support BIOS dual-booting. However, customizing TrueOS by replacing rEFInd with a BIOS friendly boot manager could theoretically get it working. However, those kind of customizations are just a bit too tricky and time-consuming to be an officially supported part of TrueOS (at least for now).

**Comment by danboid** [comment]
Hi Tim

I have installed the latest TrueOS on my i7, BIOS-based laptop and it seems to use the FreeBSD bootloader on such machines. I take your response as confirmation that dual-booting with the FreeBSD bootloader (ie on a non-UEFI, single disk machine) isn't possible yet.

Thanks
