### ISSUE TITLE
Clicking the TrueOS translate button takes you to a translate FreeNAS screen

### ISSUE THREAD

**Issue by JoshDW19** [trueos/trueos-docs#37]
![image](https://user-images.githubusercontent.com/6586006/26889287-b0c65312-4b7b-11e7-8bc9-5fc8afc021bc.png)

You have to click "tools" > "all projects" > "trueos-utils-qt5" to get to the TrueOS utilities.

**Comment by Mrt134** [comment]
Sorry it took so long - I got confused and thought this was an issue with the website itself, not the link in the handbook.
