### ISSUE TITLE
Makefile:13: *** missing separator. Stop.

### ISSUE THREAD

**Issue by g000444555** [trueos/trueos-docs#4]
I get the following error when trying to make the handbook on ubuntu 16.04 LTS:

```
$ cd trueos-handbook
$ make epub
Makefile:13: *** missing separator. Stop.
```

**Comment by kmoore134** [comment]
Yea, I do see this error when using 'gmake'. Not sure the issue yet, works with FreeBSD's make.

**Comment by patryk-s** [comment]
gmake doesn't like the period before "ifndef" and "endif" but if you remove them it stops on line 75 on:

    .if exists(po)

but I don't know how to fix that one - it also doesn't like the period-less "if":

    Makefile:75: *** missing separator.  Stop.

**Comment by patryk-s** [comment]
Oh, and try *bmake*:

    apt-get install bmake

**Comment by beanpole135** [comment]
Well, the handbook is already available pre-built on the website[1]. Since TrueOS is an operating system, we kind of expect that the handbook to be "built" on the same operating system, not other types of systems.

Closing as "not to be fixed".

[1] https://www.trueos.org/handbook/trueos.html
