### ISSUE TITLE
Misuse of the word 'zpool' in TrueOS Disk Wizard, in TrueOS Text Install - Edit Menu and in Life Preserver

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-docs#5]
Related: https://github.com/trueos/trueos-core/issues/85 

The word appears under: 
- https://www.trueos.org/handbook/install.html?highlight=zpool#install9b
- https://www.trueos.org/handbook/advanced.html?highlight=zpool#text11a
- https://www.trueos.org/handbook/sysadmclient.html?highlight=zpool#lpreserver5

**Comment by baitisj** [comment]
I think I got all the code level changes here. Waiting for a new roll of the installer so I can update the screenshots.

**Comment by baitisj** [comment]
Also, here's a great document that describes proper ZFS nomenclature:
https://docs.oracle.com/cd/E18752_01/html/819-5461/ftyue.html

**Comment by pkgdemon** [comment]
Are we still missing doc updates for this?

**Comment by baitisj** [comment]
Let me double-check something. Sorry I dropped the ball; I think I was going to update a screenshot.

**Comment by baitisj** [comment]
Unfortunately something has changed and I no longer have permission to commit to trueos-docs (?!)

**Comment by baitisj** [comment]
The SysAdm client needed a couple of screenshot updates. I have those ready to go.

@grahamperrin : FYI I made no changes to https://www.trueos.org/handbook/advanced.html?highlight=zpool#text11a because of space concerns in the ncurses environment

Could do one more code-level change for https://www.trueos.org/handbook/sysadmclient.html?highlight=zpool#snapshots-tab and change "ZFS Pool" to "Storage Pool" for consistency. Let me know if you think this is warranted.

**Comment by grahamperrin** [comment]
I reckon just 'Pool:', because it falls below the word 'Snapshots'

**Comment by baitisj** [comment]
Ok, I haven't pushed the code-level modification to the repository yet, but @grahamperrin please let me know what you think of these updated screenshots.
![lpreserver5](https://cloud.githubusercontent.com/assets/12502877/20848068/66840df0-b885-11e6-8173-4faa03616fec.png)
![lpreserver4](https://cloud.githubusercontent.com/assets/12502877/20848069/66988e74-b885-11e6-84b1-4fcbbccd0c4a.png)
![lpreserver3](https://cloud.githubusercontent.com/assets/12502877/20848071/66b83cba-b885-11e6-879a-6a049cfa649f.png)
![lpreserver2](https://cloud.githubusercontent.com/assets/12502877/20848070/66adf39a-b885-11e6-8b7c-ebdea17a0556.png)
![lpreserver1](https://cloud.githubusercontent.com/assets/12502877/20848072/66c463be-b885-11e6-8778-651e9becf0e5.png)

**Comment by baitisj** [comment]
The last appearances of the dreaded "zpool" appear in trueos-utils/src-sh/trueos-utils/pc-installdialog/pc-installdialog.sh ... and, the documentation and screenshots need to be updated once these instances are quashed. I suggest "pool" instead of "zpool" here due to ncurses space constraints. Any objections?

**Comment by baitisj** [comment]
Here's the last screenshot that needs changing. I'm ready to push everything and close this, once I have access to the repositories in question.
![text11a](https://cloud.githubusercontent.com/assets/12502877/20854840/0bcc5d00-b8ac-11e6-8b19-d691d5914117.png)

**Comment by pkgdemon** [comment]
I will make sure @kmoore134 gets that fixed.  If he had to send an invite you might just need to visit the repo to see the invite to accept.  Github does not show the notification otherwise.  I wish they would fix that.

**Comment by grahamperrin** [comment]
> … [please let me know what you think of these updated screenshots.](https://github.com/trueos/trueos-docs/issues/5#issuecomment-264545932)

All things considered, I probably do favour consistent use of the phrase _storage pool_ (or in places, simply _pool_). With uppercase initial letters where the phrase appears in a Americanised GUI, and so on. 

----

My gut tells me that some end users will find it peculiar to _not_ see the word ZFS. For these people I should probably draw attention to https://gitter.im/trueos/Lobby?at=57f1db36b0ff456d3adce3eb (and other plain English-oriented discussions, links to which I don't have handy); and to 'ZPool' in e.g. the captured page at http://wayback.archive.org/web/20161023204945/https://www.trueos.org/handbook/sysadmclient.html#schedules-tab

@baitisj a five-minute chat in https://gitter.im/trueos/Random some time over the weekend will be nice. 

----

Wording aside, now _might_ be a good time to consider another improvement to one of the GUIs pictured above. I'll take this to https://gitter.im/trueos/Lobby for thoughts …

**Comment by baitisj** [comment]
`grep` says that I got them all.
Closing this issue.
