### ISSUE TITLE
Sysadm issue trackers now up - update docs

### ISSUE THREAD

**Issue by q5sys** [trueos/trueos-docs#51]
The issue trackers for sysadm are not up and running, so we need to update docs to point there for the place to report issues instead of the trueos-core repo.

**Comment by q5sys** [comment]
https://github.com/trueos/sysadm/issues
https://github.com/trueos/sysadm-ui-qt/issues

**Comment by Mrt134** [comment]
Creating a list of repos that I've updated:
pcbsd
