### ISSUE TITLE
Translations getting cloned into all languages

### ISSUE THREAD

**Issue by SoloBSD** [trueos/trueos-docs#6]
I am doing translations for the TrueOS Guide into spanish, but I have noticed that all my translations are getting cloned into all the other active languages. Now all languages have the same percentage of completion as "es" and all the translated strings for all languages are in spanish, you can check here:

[http://weblate.trueos.org/projects/trueos-guide/](http://weblate.trueos.org/projects/trueos-guide/)

**Comment by Mrt134** [comment]
Small update: we are looking at this issue, and the wider translation system as well. We hope to have fixes/changes soon.

**Comment by Mrt134** [comment]
Weblate is now fixed and running again! However, the user guides are too large to be included in Weblate. We are looking at different solutions for the guides, but it looks like we will be doing guide translations directly through github pull requests/local po editing solutions. Keep an eye on discourse (https://discourse.trueos.org/) for more info.
