### ISSUE TITLE
Initial review of handbook:

### ISSUE THREAD

**Issue by Mrt134** [trueos/trueos-docs#60]
Pursuant to the Milestone description, the TrueOS handbook needs to be reviewed with the goal of determining how many documents to create out of it.

Currently, I'm thinking/suggesting breaking the book into three documents:
- Install guide
- User guide
- OS customisation guide

However, a more thorough review of the material may indicate a different breakdown.

**Comment by a-stjohn** [comment]
1. Introduction Document. (Essentially all the current sections in the Introduction chapter) :
     - Introduction
     - The current typographical conventions used throughout the docs
     - Legal stuff
     - The comparisons of TrueOs and other OS's
2. Just one install guide (like you've suggested).
     - I guess the idea would be "pre-install", "install", and "post-install"  will be simplified/reviewed and combined.
3. User Guide
     - Using TrueOS
          - Most of "Using TrueOS" because I feel like the documentation in "Using TrueOS" is just describing to the user how to navigate and use TrueOS.
     - TrueOS Pico?

Judging from the current TrueOS handbook I feel like an "OS customization guide" section would consist of very little information (from the current handbook) unless brand new documentation was added to it. On the other hand, I feel like "User  Guide" will take on most (maybe half) of the current TrueOS handbook.

**Comment by Mrt134** [comment]
I hadn't thought of an Introduction doc, makes a lot of sense.

If we do have a "OS customization" type doc, I have a feeling some of the elements from the "install" and "using" sections would make it in. But you're right; there may not be enough there to warrant a separate doc.

Pico may actually be good as a separate document, but I'll have to look at it a bit more closely.

**Comment by Mrt134** [comment]
Brand new thought hit me - what about another very short doc discussing the ins and outs of dual-booting the OS? It could be worked into the install doc, but might be better as its own guide so as to keep the install instructions as simple as possible.

**Comment by a-stjohn** [comment]
Analysis on TrueOS Handbook Docs:
**1. Introduction Document.**
     - Contains what is already listed in the handbook for "Introduction".
**2. Install Document.**
     - Contains "Pre-install" section with, perhaps, the virtualization section put into a separate doc.
     - Contains "Install" section. "Advanced Installation Topics" could be inserted into a separate doc as well.
     - Contains "Post-install" section. Also, "Managing System Services and Daemons" could be inserted into a separate doc.
**3. Help and Support Document.**
     - Contains all the info in the "Help and Support" section.
**4. User Guide.**
     - Contains everything from the "Using TrueOS" section.
     - Could add another section that would include the above mentioned sections that were left out of the new "Install" document.
     - Also, another section could be added about Dual-booting. However, I'm not sure if it would fit into this new document.
**5. TrueOS Pico?**
     - Still in question whether or not it could be a separate document.

**Comment by a-stjohn** [comment]
According to some feedback we are now considering reworking the handbook a different way, keeping it as one document. Each section will be reviewed so that the most desired information is displayed clearly and effectively. In regards to referencing, it will try to be reduced so that users don't experience the "ping-pong" effect.

**Comment by Mrt134** [comment]
Complete
