### ISSUE TITLE
Configure Wireless image missing

### ISSUE THREAD

**Issue by ppumkin** [trueos/trueos-docs#7]
https://www.trueos.org/handbook/postinstall.html#connect-to-a-wireless-network

Also.. I am an unfortunate Broadcom WiFi device holder and an extreme newbie. Struggling to get Wifi to work.

What can I do? There seems to be very little help in the documents how to solve this problem. 

I eventually rumaged around for an Intel card and got it going.. but not the first time either. Just saying.. 

The document should say.. Sorry Broadcom not supported - Dont waste your time, atleast that?!

Thanks

**Comment by Mrt134** [comment]
Thanks for your report. We do have a section in the preinstallation chapter detailing how to find supported hardware, with the Broadcom issues specifically mentioned: https://www.trueos.org/handbook/preinstall.html#supported-hardware. I've added a note linking to this section of the handbook to the postinstallation chapter you were referencing.
