### ISSUE TITLE
The README for pc-sysinstall is not consistent with the User Guide for TrueOS

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-docs#8]
(Is trueos/trueos-docs the best repo for issues such as this?)

Originally posted at https://discourse.trueos.org/t/119

According to the note above https://www.trueos.org/handbook/advanced.html?highlight=fresh#installvariables2

> The README file contains more complete descriptions for each variable.

https://github.com/trueos/pc-sysinstall/blob/b425afe9c063066c802536a9e6156ce0f8ac5387/README.md contains no such description.

## Side note

Milestone blog post [PC-BSD Evolves into TrueOS | TrueOS](https://www.trueos.org/2016/09/01/pc-bsd-evolves-into-trueos/) ([captured](http://web.archive.org/web/*/https://www.trueos.org/2016/09/01/pc-bsd-evolves-into-trueos/)) describes _fresh_ installation as _non-destructive_. 

If I understand correctly, the more recent meaning of _fresh_ is the opposite: destructive. 

Observations and thoughts from around two weeks ago: https://gitter.im/trueos/Lobby?at=5801ee6e457ae29b71dfbd40

**Comment by Mrt134** [comment]
Thanks for reporting this. The README in that case is referring to the file in /usr/local/share/pc-sysinstall/examples, as mentioned above the note, but I've reworded the note to be absolutely clear where to find the README file.
